import type { EtLayersSnapshot, ProjectAudit } from '../types/layers';

export const emptyStats = {
  layers: 0,
  text: 0,
  shapes: 0,
  nulls: 0,
  solids: 0,
  adjustments: 0,
  cameras: 0,
  lights: 0,
  locked: 0,
  hidden: 0,
  disabled: 0,
  brokenExpressions: 0,
};

export const mockSnapshot: EtLayersSnapshot = {
  comp: {
    id: 'mock-comp',
    name: 'Etvrnity Launch Film',
    layerCount: 247,
    width: 3840,
    height: 2160,
    duration: 18.4,
    frameRate: 23.976,
  },
  stats: {
    layers: 247,
    text: 18,
    shapes: 41,
    nulls: 12,
    solids: 34,
    adjustments: 9,
    cameras: 2,
    lights: 1,
    locked: 7,
    hidden: 13,
    disabled: 6,
    brokenExpressions: 0,
  },
  layers: [
    {
      id: '1',
      index: 1,
      name: 'Logo',
      normalizedName: 'logo',
      type: 'shape',
      compId: 'mock-comp',
      compName: 'Etvrnity Launch Film',
      compPath: ['Etvrnity Launch Film'],
      breadcrumb: 'Etvrnity Launch Film',
      groupId: 'mock-comp',
      groupName: 'Etvrnity Launch Film',
      locked: false,
      shy: false,
      enabled: true,
      selected: false,
      solo: false,
      parented: false,
      parentName: '',
      label: 8,
      labelName: 'Blue',
      inPoint: 0,
      outPoint: 18.4,
    },
    {
      id: '2',
      index: 2,
      name: 'Logo Glow',
      normalizedName: 'logo glow',
      type: 'solid',
      compId: 'mock-precomp-logo',
      compName: 'Logo Precomp',
      compPath: ['Etvrnity Launch Film', 'Logo Precomp'],
      breadcrumb: 'Etvrnity Launch Film > Logo Precomp',
      groupId: 'mock-precomp-logo',
      groupName: 'Logo Precomp',
      locked: false,
      shy: false,
      enabled: true,
      selected: false,
      solo: false,
      parented: false,
      parentName: '',
      label: 2,
      labelName: 'Yellow',
      inPoint: 0.4,
      outPoint: 18.4,
    },
    {
      id: '3',
      index: 3,
      name: 'Main Camera',
      normalizedName: 'main camera',
      type: 'camera',
      compId: 'mock-comp',
      compName: 'Etvrnity Launch Film',
      compPath: ['Etvrnity Launch Film'],
      breadcrumb: 'Etvrnity Launch Film',
      groupId: 'mock-comp',
      groupName: 'Etvrnity Launch Film',
      locked: false,
      shy: false,
      enabled: true,
      selected: false,
      solo: false,
      parented: false,
      parentName: '',
      label: 10,
      labelName: 'Purple',
      inPoint: 0,
      outPoint: 18.4,
    },
    {
      id: '4',
      index: 4,
      name: 'Headline Text',
      normalizedName: 'headline text',
      type: 'text',
      compId: 'mock-precomp-title',
      compName: 'Title Precomp',
      compPath: ['Etvrnity Launch Film', 'Intro', 'Title Precomp'],
      breadcrumb: 'Etvrnity Launch Film > Intro > Title Precomp',
      groupId: 'mock-precomp-title',
      groupName: 'Title Precomp',
      locked: false,
      shy: false,
      enabled: true,
      selected: false,
      solo: false,
      parented: true,
      parentName: 'Logo Controller',
      label: 11,
      labelName: 'Orange',
      inPoint: 2,
      outPoint: 9,
    },
  ],
  projectFingerprint: 'mock-project',
  refreshedAt: String(Date.now()),
};

export const mockProjectAudit: ProjectAudit = {
  fingerprint: 'mock-project',
  groups: [
    {
      type: 'missingFootage',
      label: 'Missing Footage',
      count: 3,
      issues: [
        {
          id: 'missing-1',
          type: 'missingFootage',
          status: 'Missing',
          severity: 'error',
          icon: '!',
          name: 'hero_plate.mov',
          detail: '/Volumes/Archive/hero_plate.mov',
          itemId: 'footage-1',
          itemKind: 'footage',
        },
      ],
    },
    {
      type: 'unusedFootage',
      label: 'Unused Footage',
      count: 42,
      issues: [],
    },
    {
      type: 'emptyComps',
      label: 'Empty Comps',
      count: 7,
      issues: [],
    },
  ],
};
